### ISSUE TITLE
Add Angular 1.x Example

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/why-frameworks-matter#3]

**Comment by manjunatha-d** [comment]
@rwieruch, which version of Angular are you looking for? I'm familiar with AngularJS 1.x, I can add that example using 1.x if that's alright.

**Comment by rwieruch** [comment]
Sure! 👍  I think it would be great to see the evolution from Angular 1.x to Angular X. 

Let me know if you need any help! It would be great to have it pretty similar to the Vue/React scenarios. It should be possible to run the index.js and index.html with the simple http-server :)

**Comment by manjunatha-d** [comment]
Sure👍I'll raise a pull request soon.
