### ISSUE TITLE
Add Angular X Example

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/why-frameworks-matter#5]

**Comment by nioperas06** [comment]
Can I work on this?

**Comment by rwieruch** [comment]
Sure! I would love to welcome any Angular addition here :)

**Comment by nioperas06** [comment]
Should I create a project with Angular CLI or Setting Up Angular App from Scratch. Every example contains only `index.html` and `index.js` files. Angular breaks the mood 🤔

**Comment by rwieruch** [comment]
Isn't it possible to create an angular project from scratch with an index.html and index.js file? After all, it should be possible with HTML and JS, shouldn't it? :)
